/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author JEMG
 */
public class Administracion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Administracion.class.getName());

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
        setIconImage(new ImageIcon("recursos/logo_peque.png").getImage());
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        btnSalirA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Escudo1 = new javax.swing.JLabel();
        btnIniciarV = new javax.swing.JButton();
        TotalV = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Escudo2 = new javax.swing.JLabel();
        VotantesN = new javax.swing.JLabel();
        TotalV1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        Escudo4 = new javax.swing.JLabel();
        CandidatosN = new javax.swing.JLabel();
        EditarC = new javax.swing.JButton();
        TotalV2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Escudo = new javax.swing.JLabel();
        VotosN = new javax.swing.JLabel();
        TotalV3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setSize(new java.awt.Dimension(1920, 1080));

        jPanel1.setBackground(new java.awt.Color(3, 17, 41));

        Logo.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\Logo.png")); // NOI18N

        btnSalirA.setBackground(new java.awt.Color(109, 80, 218));
        btnSalirA.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSalirA.setForeground(new java.awt.Color(34, 32, 86));
        btnSalirA.setText("SALIR");
        btnSalirA.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnSalirA.setContentAreaFilled(false);
        btnSalirA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalirA.setOpaque(true);
        btnSalirA.addActionListener(this::btnSalirAActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnSalirA, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalirA, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
        );

        Logo.getAccessibleContext().setAccessibleName("logo");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 32, 86));
        jLabel2.setText("Panel de administración");

        Escudo1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\Escudo3 (1).png")); // NOI18N

        btnIniciarV.setBackground(new java.awt.Color(109, 80, 218));
        btnIniciarV.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIniciarV.setForeground(new java.awt.Color(34, 32, 86));
        btnIniciarV.setText("INICIAR \nVOTACIONES");
        btnIniciarV.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnIniciarV.setContentAreaFilled(false);
        btnIniciarV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIniciarV.setOpaque(true);
        btnIniciarV.addActionListener(this::btnIniciarVActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(Escudo1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIniciarV, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIniciarV, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Escudo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnIniciarV.getAccessibleContext().setAccessibleName("");

        TotalV.setBackground(new java.awt.Color(255, 255, 255));
        TotalV.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        TotalV.setPreferredSize(new java.awt.Dimension(260, 180));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 32, 86));
        jLabel3.setText("Total votantes");

        Escudo2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\personitas-removebg-preview (2).png")); // NOI18N
        Escudo2.setPreferredSize(new java.awt.Dimension(50, 50));

        VotantesN.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        VotantesN.setForeground(new java.awt.Color(34, 32, 86));
        VotantesN.setText("0");

        javax.swing.GroupLayout TotalVLayout = new javax.swing.GroupLayout(TotalV);
        TotalV.setLayout(TotalVLayout);
        TotalVLayout.setHorizontalGroup(
            TotalVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TotalVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TotalVLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(VotantesN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39))
        );
        TotalVLayout.setVerticalGroup(
            TotalVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalVLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TotalVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Escudo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TotalVLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(VotantesN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalV1.setBackground(new java.awt.Color(255, 255, 255));
        TotalV1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 32, 86));
        jLabel6.setText("Candidatos");

        Escudo4.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\personitas-removebg-preview (2).png")); // NOI18N
        Escudo4.setPreferredSize(new java.awt.Dimension(50, 50));

        CandidatosN.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        CandidatosN.setForeground(new java.awt.Color(34, 32, 86));
        CandidatosN.setText("0");

        EditarC.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        EditarC.setForeground(new java.awt.Color(34, 32, 86));
        EditarC.setText("Editar");
        EditarC.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        EditarC.setContentAreaFilled(false);
        EditarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarC.addActionListener(this::EditarCActionPerformed);

        javax.swing.GroupLayout TotalV1Layout = new javax.swing.GroupLayout(TotalV1);
        TotalV1.setLayout(TotalV1Layout);
        TotalV1Layout.setHorizontalGroup(
            TotalV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalV1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(TotalV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalV1Layout.createSequentialGroup()
                        .addComponent(Escudo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TotalV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CandidatosN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalV1Layout.createSequentialGroup()
                        .addComponent(EditarC, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        TotalV1Layout.setVerticalGroup(
            TotalV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalV1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(TotalV1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Escudo4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TotalV1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(CandidatosN)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(EditarC)
                .addContainerGap())
        );

        TotalV2.setBackground(new java.awt.Color(255, 255, 255));
        TotalV2.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 32, 86));
        jLabel4.setText("Votos Emitidos");

        Escudo.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\VOTOD.png")); // NOI18N
        Escudo.setPreferredSize(new java.awt.Dimension(50, 50));

        VotosN.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        VotosN.setForeground(new java.awt.Color(34, 32, 86));
        VotosN.setText("0");

        javax.swing.GroupLayout TotalV2Layout = new javax.swing.GroupLayout(TotalV2);
        TotalV2.setLayout(TotalV2Layout);
        TotalV2Layout.setHorizontalGroup(
            TotalV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TotalV2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Escudo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TotalV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VotosN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        TotalV2Layout.setVerticalGroup(
            TotalV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalV2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(TotalV2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Escudo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(TotalV2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(26, 26, 26)
                        .addComponent(VotosN)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TotalV3.setBackground(new java.awt.Color(255, 255, 255));
        TotalV3.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(153, 153, 153)));
        TotalV3.setPreferredSize(new java.awt.Dimension(260, 180));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 32, 86));
        jLabel5.setText("Proceso de votación");

        javax.swing.GroupLayout TotalV3Layout = new javax.swing.GroupLayout(TotalV3);
        TotalV3.setLayout(TotalV3Layout);
        TotalV3Layout.setHorizontalGroup(
            TotalV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalV3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        TotalV3Layout.setVerticalGroup(
            TotalV3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TotalV3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel5)
                .addContainerGap(341, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(153, 153, 153)
                                .addComponent(TotalV3, javax.swing.GroupLayout.PREFERRED_SIZE, 1017, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 381, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(TotalV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalV2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(TotalV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TotalV, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                    .addComponent(TotalV2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TotalV1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(TotalV3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarCActionPerformed
        // TODO add your handling code here:
        
    EditarCandidatos dialog = new EditarCandidatos(this, true);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    }//GEN-LAST:event_EditarCActionPerformed

    private void btnSalirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro que desea salir?", 
        "Cerrar Sesión", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if(confirmar == JOptionPane.YES_OPTION) {
        // Cerrar ventana de administración
        dispose();
        
        // Volver a abrir el Login
        LoginAdmin login = new LoginAdmin();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
    }
        
        
        
    }//GEN-LAST:event_btnSalirAActionPerformed

    private void btnIniciarVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarVActionPerformed
        // TODO add your handling code here:
         // Mensaje de confirmación
    int confirmar = JOptionPane.showConfirmDialog(this, 
        "¿Está seguro de iniciar la votación?", 
        "Confirmar", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if(confirmar == JOptionPane.YES_OPTION) {
        // Cerrar ventana actual (opcional)
        dispose();
        
        // Abrir el JFrame RegistraTuVoto
        RegistraTuvoto ventanaVoto = new RegistraTuvoto();
        ventanaVoto.setLocationRelativeTo(null);  // Centrar
        ventanaVoto.setVisible(true);
        
        // Mensaje opcional
        JOptionPane.showMessageDialog(this, "Votación iniciada correctamente");
    }
        
        
    }//GEN-LAST:event_btnIniciarVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Administracion().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CandidatosN;
    private javax.swing.JButton EditarC;
    private javax.swing.JLabel Escudo;
    private javax.swing.JLabel Escudo1;
    private javax.swing.JLabel Escudo2;
    private javax.swing.JLabel Escudo4;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel TotalV;
    private javax.swing.JPanel TotalV1;
    private javax.swing.JPanel TotalV2;
    private javax.swing.JPanel TotalV3;
    private javax.swing.JLabel VotantesN;
    private javax.swing.JLabel VotosN;
    private javax.swing.JButton btnIniciarV;
    private javax.swing.JButton btnSalirA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
