/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author JEMG
 */
public class EditarCandidatos extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditarCandidatos.class.getName());

    /**
     * Creates new form EditarCandidatos
     */
    public EditarCandidatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon("recursos/logo_peque.png").getImage());
        
        estilizarBoton(EditarN);
        estilizarBoton(EditarN1);
        estilizarBoton(EditarN2);
        estilizarBoton(EditarN3);
        
    }
   
    
    private void estilizarBoton(JButton boton) {
    boton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 32, 86), 2));
    boton.setContentAreaFilled(false);
    boton.setOpaque(true);
    boton.setBackground(new java.awt.Color(34, 32, 86));
    boton.setForeground(java.awt.Color.WHITE);
    boton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(34, 32, 86), 2, true));
}
    
 
    
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Foto = new javax.swing.JButton();
        Foto1 = new javax.swing.JButton();
        Foto2 = new javax.swing.JButton();
        Foto3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNombreCompleto = new javax.swing.JLabel();
        EditarN = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombreCompleto1 = new javax.swing.JLabel();
        EditarN1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNombreCompleto2 = new javax.swing.JLabel();
        EditarN2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblNombreCompleto3 = new javax.swing.JLabel();
        EditarN3 = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Foto.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto.setContentAreaFilled(false);
        Foto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto.addActionListener(this::FotoActionPerformed);

        Foto1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto1.setContentAreaFilled(false);
        Foto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto1.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto1.addActionListener(this::Foto1ActionPerformed);

        Foto2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto2.setContentAreaFilled(false);
        Foto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto2.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto2.addActionListener(this::Foto2ActionPerformed);

        Foto3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto3.setContentAreaFilled(false);
        Foto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto3.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto3.addActionListener(this::Foto3ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto.setText("Nombres y Apellidos");

        EditarN.setText("<html> <font size=\"5\">✏️</font> </html>");
        EditarN.setBorder(null);
        EditarN.setContentAreaFilled(false);
        EditarN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarN.addActionListener(this::EditarNActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblNombreCompleto, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(EditarN, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lblNombreCompleto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EditarN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCompleto1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto1.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto1.setText("Nombres y Apellidos");

        EditarN1.setText("<html> <font size=\"5\">✏️</font> </html>");
        EditarN1.setBorder(null);
        EditarN1.setContentAreaFilled(false);
        EditarN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarN1.addActionListener(this::EditarN1ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombreCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(EditarN1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCompleto1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCompleto2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto2.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto2.setText("Nombres y Apellidos");

        EditarN2.setText("<html> <font size=\"5\">✏️</font> </html>");
        EditarN2.setBorder(null);
        EditarN2.setContentAreaFilled(false);
        EditarN2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarN2.addActionListener(this::EditarN2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombreCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(EditarN2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreCompleto3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto3.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto3.setText("Nombres y Apellidos");

        EditarN3.setText("<html> <font size=\"5\">✏️</font> </html>");
        EditarN3.setBorder(null);
        EditarN3.setContentAreaFilled(false);
        EditarN3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EditarN3.addActionListener(this::EditarN3ActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNombreCompleto3, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(EditarN3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombreCompleto3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditarN3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setBackground(new java.awt.Color(109, 80, 218));
        btnGuardar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(3, 17, 41));
        btnGuardar.setText("Guardar Cambios");
        btnGuardar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(true);
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto3, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Foto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Foto1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Foto2, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FotoActionPerformed
        // TODO add your handling code here:
          JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto.setIcon(new ImageIcon(img));
    Foto.revalidate();
    Foto.repaint();
    }
        
        
        
    }//GEN-LAST:event_FotoActionPerformed

    private void Foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto1ActionPerformed
        // TODO add your handling code here:
                  JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto1.setIcon(new ImageIcon(img));
    Foto1.revalidate();
    Foto1.repaint();
    }//GEN-LAST:event_Foto1ActionPerformed
    }
    private void Foto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto2ActionPerformed
        // TODO add your handling code here:
        
                          JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto2.setIcon(new ImageIcon(img));
    Foto2.revalidate();
    Foto2.repaint();
        

      }  
    }//GEN-LAST:event_Foto2ActionPerformed

    private void Foto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto3ActionPerformed
        // TODO add your handling code here:
     JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto3.setIcon(new ImageIcon(img));
    Foto3.revalidate();
    Foto3.repaint();

      }   
        
    }//GEN-LAST:event_Foto3ActionPerformed

    private void EditarNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarNActionPerformed
        // TODO add your handling code here:
        
    String textoActual = lblNombreCompleto.getText();
    
    String nuevoTexto = JOptionPane.showInputDialog(this, "Editar nombre del candidato:", textoActual);
    
    if (nuevoTexto != null && !nuevoTexto.trim().isEmpty()) {
        lblNombreCompleto.setText(nuevoTexto);
    }
        
        
        
    }//GEN-LAST:event_EditarNActionPerformed

    private void EditarN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarN1ActionPerformed
        // TODO add your handling code here:
                
    String textoActual = lblNombreCompleto1.getText();
    
    String nuevoTexto = JOptionPane.showInputDialog(this, "Editar nombre del candidato:", textoActual);
    
    if (nuevoTexto != null && !nuevoTexto.trim().isEmpty()) {
        lblNombreCompleto1.setText(nuevoTexto);
    }
        
        
        
        
        
    }//GEN-LAST:event_EditarN1ActionPerformed

    private void EditarN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarN2ActionPerformed
        // TODO add your handling code here:
            String textoActual = lblNombreCompleto2.getText();
    
    String nuevoTexto = JOptionPane.showInputDialog(this, "Editar nombre del candidato:", textoActual);
    
    if (nuevoTexto != null && !nuevoTexto.trim().isEmpty()) {
        lblNombreCompleto2.setText(nuevoTexto);
    }
        
        
        
    }//GEN-LAST:event_EditarN2ActionPerformed

    private void EditarN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarN3ActionPerformed
        // TODO add your handling code here:
        
    String textoActual = lblNombreCompleto3.getText();
    
    String nuevoTexto = JOptionPane.showInputDialog(this, "Editar nombre del candidato:", textoActual);
    
    if (nuevoTexto != null && !nuevoTexto.trim().isEmpty()) {
        lblNombreCompleto3.setText(nuevoTexto);
    }
        
        
        
    }//GEN-LAST:event_EditarN3ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        
            JOptionPane.showMessageDialog(this, "Cambios guardados");
    dispose();
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                EditarCandidatos dialog = new EditarCandidatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditarN;
    private javax.swing.JButton EditarN1;
    private javax.swing.JButton EditarN2;
    private javax.swing.JButton EditarN3;
    private javax.swing.JButton Foto;
    private javax.swing.JButton Foto1;
    private javax.swing.JButton Foto2;
    private javax.swing.JButton Foto3;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblNombreCompleto1;
    private javax.swing.JLabel lblNombreCompleto2;
    private javax.swing.JLabel lblNombreCompleto3;
    // End of variables declaration//GEN-END:variables
}
