/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author JEMG
 */
public class Votacion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Votacion.class.getName());

    /**
     * Creates new form EditarCandidatos
     */
    public Votacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setIconImage(new ImageIcon("recursos/logo_peque.png").getImage());
        
  
        
    }
   
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Foto = new javax.swing.JButton();
        Foto1 = new javax.swing.JButton();
        Foto2 = new javax.swing.JButton();
        Foto3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblNombreCompleto = new javax.swing.JLabel();
        btnVotar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblNombreCompleto1 = new javax.swing.JLabel();
        btnVotar2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblNombreCompleto2 = new javax.swing.JLabel();
        btnVotar3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        lblNombreCompleto3 = new javax.swing.JLabel();
        btnVotar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Foto.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto.setContentAreaFilled(false);
        Foto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto.addActionListener(this::FotoActionPerformed);

        Foto1.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto1.setContentAreaFilled(false);
        Foto1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto1.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto1.addActionListener(this::Foto1ActionPerformed);

        Foto2.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto2.setContentAreaFilled(false);
        Foto2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto2.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto2.addActionListener(this::Foto2ActionPerformed);

        Foto3.setIcon(new javax.swing.ImageIcon("C:\\Users\\JEMG\\Documents\\NetBeansProjects\\Voto Digital\\recursos\\editarcandidato (1).png")); // NOI18N
        Foto3.setContentAreaFilled(false);
        Foto3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foto3.setPreferredSize(new java.awt.Dimension(100, 100));
        Foto3.addActionListener(this::Foto3ActionPerformed);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto.setText("Nombres y Apellidos");
        jPanel1.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 16, 499, -1));

        btnVotar1.setBackground(new java.awt.Color(109, 80, 218));
        btnVotar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVotar1.setForeground(new java.awt.Color(3, 17, 41));
        btnVotar1.setText("Votar");
        btnVotar1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnVotar1.setContentAreaFilled(false);
        btnVotar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVotar1.setOpaque(true);
        btnVotar1.addActionListener(this::btnVotar1ActionPerformed);
        jPanel1.add(btnVotar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 30));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto1.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto1.setText("Nombres y Apellidos");
        jPanel2.add(lblNombreCompleto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 370, 38));

        btnVotar2.setBackground(new java.awt.Color(109, 80, 218));
        btnVotar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVotar2.setForeground(new java.awt.Color(3, 17, 41));
        btnVotar2.setText("Votar");
        btnVotar2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnVotar2.setContentAreaFilled(false);
        btnVotar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVotar2.setOpaque(true);
        btnVotar2.addActionListener(this::btnVotar2ActionPerformed);
        jPanel2.add(btnVotar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, 30));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto2.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto2.setText("Nombres y Apellidos");
        jPanel3.add(lblNombreCompleto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 380, 38));

        btnVotar3.setBackground(new java.awt.Color(109, 80, 218));
        btnVotar3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVotar3.setForeground(new java.awt.Color(3, 17, 41));
        btnVotar3.setText("Votar");
        btnVotar3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnVotar3.setContentAreaFilled(false);
        btnVotar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVotar3.setOpaque(true);
        btnVotar3.addActionListener(this::btnVotar3ActionPerformed);
        jPanel3.add(btnVotar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, 100, 30));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombreCompleto3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblNombreCompleto3.setForeground(new java.awt.Color(3, 17, 41));
        lblNombreCompleto3.setText("Nombres y Apellidos");
        jPanel4.add(lblNombreCompleto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 6, 499, 38));

        btnVotar4.setBackground(new java.awt.Color(109, 80, 218));
        btnVotar4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnVotar4.setForeground(new java.awt.Color(3, 17, 41));
        btnVotar4.setText("Votar");
        btnVotar4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        btnVotar4.setContentAreaFilled(false);
        btnVotar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVotar4.setOpaque(true);
        btnVotar4.addActionListener(this::btnVotar4ActionPerformed);
        jPanel4.add(btnVotar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(59, 59, 59))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Foto1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Foto2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Foto3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FotoActionPerformed
        // TODO add your handling code here:
          JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto.setIcon(new ImageIcon(img));
    Foto.revalidate();
    Foto.repaint();
    }
        
        
        
    }//GEN-LAST:event_FotoActionPerformed

    private void Foto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto1ActionPerformed
        // TODO add your handling code here:
                  JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto1.setIcon(new ImageIcon(img));
    Foto1.revalidate();
    Foto1.repaint();
    }//GEN-LAST:event_Foto1ActionPerformed
    }
    private void Foto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto2ActionPerformed
        // TODO add your handling code here:
        
                          JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto2.setIcon(new ImageIcon(img));
    Foto2.revalidate();
    Foto2.repaint();
        

      }  
    }//GEN-LAST:event_Foto2ActionPerformed

    private void Foto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Foto3ActionPerformed
        // TODO add your handling code here:
     JFileChooser fc = new JFileChooser();
    int resultado = fc.showOpenDialog(this);
    
    if(resultado == JFileChooser.APPROVE_OPTION) {
    String ruta = fc.getSelectedFile().getAbsolutePath();
    ImageIcon icono = new ImageIcon(ruta);
    
    // Escalar al tamaño fijo de 100x100
    Image img = icono.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
    
    Foto3.setIcon(new ImageIcon(img));
    Foto3.revalidate();
    Foto3.repaint();

      }   
        
    }//GEN-LAST:event_Foto3ActionPerformed

    private void btnVotar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar1ActionPerformed
      int confirmar = JOptionPane.showConfirmDialog(this, 
    "¿Está seguro de su Voto?", 
    "Votación", 
    JOptionPane.YES_NO_OPTION,
    JOptionPane.QUESTION_MESSAGE);

    if (confirmar == JOptionPane.YES_OPTION) {
    // Mensaje de agradecimiento
    JOptionPane.showMessageDialog(this, "Gracias por Votar :D");
    
    // Cerrar ventana actual (RegistraTuvoto)
    dispose();
    
    // Volver a abrir el Login (o la ventana que corresponda)

}
        
        
    }//GEN-LAST:event_btnVotar1ActionPerformed

    private void btnVotar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotar2ActionPerformed

    private void btnVotar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotar3ActionPerformed

    private void btnVotar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVotar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVotar4ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Votacion dialog = new Votacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Foto;
    private javax.swing.JButton Foto1;
    private javax.swing.JButton Foto2;
    private javax.swing.JButton Foto3;
    private javax.swing.JButton btnVotar1;
    private javax.swing.JButton btnVotar2;
    private javax.swing.JButton btnVotar3;
    private javax.swing.JButton btnVotar4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblNombreCompleto1;
    private javax.swing.JLabel lblNombreCompleto2;
    private javax.swing.JLabel lblNombreCompleto3;
    // End of variables declaration//GEN-END:variables
}
